name: Deploy to EC2

on:
  push:
    branches:
      - main # or the branch you want to deplo

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy code to EC2
      uses: appleboy/scp-action@master
      with:
        host: 18.232.83.38
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: ./
        target: /home/ubuntu/copy_paste

    - name: SSH into EC2 and restart the app (if needed)
      run: |
        ssh -i ${{ secrets.DEPLOY_KEY }} ubuntu@18.232.83.38 "cd /home/ubuntu/copy_paste"
