name: Build and Push Image to AWS ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%B-%Y')"

      - name: Get Current Time
        id: time
        run: echo "::set-output name=time::$(date +'%H-%M-%S')"

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker_push
          DATE_TAG: ${{ steps.date.outputs.date }}
          TIME_TAG: ${{ steps.time.outputs.time }}
          IMAGE_TAG: $DATE_TAG-$TIME_TAG  # Combine date and time
        run: |
          echo "Image Tag: $IMAGE_TAG"
          # Build and tag the image with the combined date and time
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Tag the image as "latest" and push it
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
