name: Copy to EC2

on:
  push:
    branches:
      - main # Change this to match your main branc

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      run: |
        scp -i ${{ secrets.EC2_SSH_KEY }} -r ./ 18.232.83.38:/home/ubuntu/copy_paste/
