name: Build and Push Image to AWS ECR
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%B-%Y')"

      - name: Get Current Version
        id: get-version
        run: |
         existing_version=$(aws ecr describe-images --repository-name docker_push --query 'images[0].imageTag' --output text)
         if [ -z "$existing_version" ]; then
         echo "::set-output name=version::v0.1.0"
         else
         echo "Existing Version: $existing_version"
         echo "::set-output name=version::$existing_version"
         fi
         
      - name: Increment Version
        id: increment-version
        run: |
          current_version=${{ steps.get-version.outputs.version }}
          IFS='.' read -ra version_parts <<< "$current_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          ((patch++))
          new_version="v$major.$minor.$patch"
          echo "::set-output name=version::${new_version}"

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker_push
          IMAGE_TAG: ${{ steps.date.outputs.date }}-${{ steps.increment-version.outputs.version }}
        run: |
          echo "Image Tag: $IMAGE_TAG"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
