name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t fasih568/image:latest .
        # Replace 'your-dockerhub-username' with your actual DockerHub username.

      - name: Push Docker Image
        run: docker push fasih568/image:latest
        # Replace 'your-dockerhub-username' with your actual DockerHub username.
